application: dmangame-hrd
version: 11
runtime: python27
api_version: 1
threadsafe: no


handlers:
- url: /media
  static_dir: media

- url: /.*
  script: appengine/appengine.py

- url: /ladder/run
  script: appengine/appengine.py
  login: admin

builtins:
- deferred: on

