application: dmangame-hrd
version: 7
runtime: python
api_version: 1


handlers:
- url: /media
  static_dir: media

- url: /.*
  script: appengine/appengine.py

- url: /ladder/run
  script: appengine/appengine.py
  login: admin

builtins:
- deferred: on
- datastore_admin: on

