# MAP MODIFIERS
MAP_SIZE=200
# BUILDING MODIFIERS
CAPTURE_LENGTH=3
UNIT_SPAWN_MOD=CAPTURE_LENGTH*10
# STAT MODIFIERS
ARMOR_MODIFIER       = 1
ATTACK_MODIFIER      = 0.5
ENERGY_MODIFIER      = 20
SIGHT_MODIFIER       = 0.8
BULLET_RANGE_MODIFIER = 10
BULLET_SPEED_MODIFIER = 40

ADDITIONAL_BUILDINGS_PER_AI=1
