# MAP MODIFIERS
MAP_SIZE=250
MAP_NAME="Warzone"
# BUILDING MODIFIERS
CAPTURE_LENGTH=5
UNIT_SPAWN_MOD=30
# STAT MODIFIERS
ARMOR_MODIFIER       = 1
ATTACK_MODIFIER      = 1
ENERGY_MODIFIER      = 20
SIGHT_MODIFIER       = 0.8
BULLET_RANGE_MODIFIER = 10
BULLET_SPEED_MODIFIER = 10

ADDITIONAL_BUILDINGS_PER_AI=2

BUILDING_SPAWN_DISTANCE=15
GAME_LENGTH=1500
