# MAP MODIFIERS
MAP_SIZE=350
# BUILDING MODIFIERS
CAPTURE_LENGTH=3
UNIT_SPAWN_MOD=CAPTURE_LENGTH*10
# STAT MODIFIERS
ARMOR_MODIFIER       = 1
ATTACK_MODIFIER      = 0.5
ENERGY_MODIFIER      = 10
SIGHT_MODIFIER       = 0.3
BULLET_RANGE_MODIFIER = 16
BULLET_SPEED_MODIFIER = 10

ADDITIONAL_BUILDINGS = 25
