# MAP MODIFIERS
MAP_SIZE=100
ADDITIONAL_BUILDINGS=0
ADDITIONAL_BUILDINGS_PER_AI=0

# BUILDING MODIFIERS
CAPTURE_LENGTH=3
UNIT_SPAWN_MOD=CAPTURE_LENGTH*10

# STAT MODIFIERS
ARMOR_MODIFIER       = 1
ATTACK_MODIFIER      = 0.5
ENERGY_MODIFIER      = 10
SIGHT_MODIFIER       = 1
SPEED_MODIFIER       = 1
BULLET_RANGE_MODIFIER = 8
BULLET_SPEED_MODIFIER = 10
